.PHONY: clean All

All:
	@echo "----------Building project:[ determinanteA - Debug ]----------"
	@cd "determinanteA" && "$(MAKE)" -f  "determinanteA.mk"
clean:
	@echo "----------Cleaning project:[ determinanteA - Debug ]----------"
	@cd "determinanteA" && "$(MAKE)" -f  "determinanteA.mk" clean
