.PHONY: clean All

All:
	@echo "----------Building project:[ arbol - Debug ]----------"
	@cd "arbol" && "$(MAKE)" -f  "arbol.mk"
clean:
	@echo "----------Cleaning project:[ arbol - Debug ]----------"
	@cd "arbol" && "$(MAKE)" -f  "arbol.mk" clean
