.PHONY: clean All

All:
	@echo "----------Building project:[ test3 - Debug ]----------"
	@cd "test3" && "$(MAKE)" -f  "test3.mk"
clean:
	@echo "----------Cleaning project:[ test3 - Debug ]----------"
	@cd "test3" && "$(MAKE)" -f  "test3.mk" clean
