.PHONY: clean All

All:
	@echo "----------Building project:[ clasesA - Debug ]----------"
	@cd "clasesA" && "$(MAKE)" -f  "clasesA.mk"
clean:
	@echo "----------Cleaning project:[ clasesA - Debug ]----------"
	@cd "clasesA" && "$(MAKE)" -f  "clasesA.mk" clean
