.PHONY: clean All

All:
	@echo "----------Building project:[ retornaVector - Debug ]----------"
	@cd "retornaVector" && "$(MAKE)" -f  "retornaVector.mk"
clean:
	@echo "----------Cleaning project:[ retornaVector - Debug ]----------"
	@cd "retornaVector" && "$(MAKE)" -f  "retornaVector.mk" clean
