.PHONY: clean All

All:
	@echo "----------Building project:[ cola - Debug ]----------"
	@cd "cola" && "$(MAKE)" -f  "cola.mk"
clean:
	@echo "----------Cleaning project:[ cola - Debug ]----------"
	@cd "cola" && "$(MAKE)" -f  "cola.mk" clean
