.PHONY: clean All

All:
	@echo "----------Building project:[ pruebaA - Debug ]----------"
	@cd "pruebaA" && "$(MAKE)" -f  "pruebaA.mk"
clean:
	@echo "----------Cleaning project:[ pruebaA - Debug ]----------"
	@cd "pruebaA" && "$(MAKE)" -f  "pruebaA.mk" clean
