.PHONY: clean All

All:
	@echo "----------Building project:[ sleepA - Debug ]----------"
	@cd "sleepA" && "$(MAKE)" -f  "sleepA.mk"
clean:
	@echo "----------Cleaning project:[ sleepA - Debug ]----------"
	@cd "sleepA" && "$(MAKE)" -f  "sleepA.mk" clean
