.PHONY: clean All

All:
	@echo "----------Building project:[ testpila - Debug ]----------"
	@cd "testpila" && "$(MAKE)" -f  "testpila.mk"
clean:
	@echo "----------Cleaning project:[ testpila - Debug ]----------"
	@cd "testpila" && "$(MAKE)" -f  "testpila.mk" clean
