.PHONY: clean All

All:
	@echo "----------Building project:[ arbolgeneral - Debug ]----------"
	@cd "arbolgeneral" && "$(MAKE)" -f  "arbolgeneral.mk"
clean:
	@echo "----------Cleaning project:[ arbolgeneral - Debug ]----------"
	@cd "arbolgeneral" && "$(MAKE)" -f  "arbolgeneral.mk" clean
