.PHONY: clean All

All:
	@echo "----------Building project:[ pilaA - Debug ]----------"
	@cd "pilaA" && "$(MAKE)" -f  "pilaA.mk"
clean:
	@echo "----------Cleaning project:[ pilaA - Debug ]----------"
	@cd "pilaA" && "$(MAKE)" -f  "pilaA.mk" clean
