.PHONY: clean All

All:
	@echo "----------Building project:[ elementosStringA - Debug ]----------"
	@cd "elementosStringA" && "$(MAKE)" -f  "elementosStringA.mk"
clean:
	@echo "----------Cleaning project:[ elementosStringA - Debug ]----------"
	@cd "elementosStringA" && "$(MAKE)" -f  "elementosStringA.mk" clean
