.PHONY: clean All

All:
	@echo "----------Building project:[ colaRecursivaA - Debug ]----------"
	@cd "colaRecursivaA" && "$(MAKE)" -f  "colaRecursivaA.mk"
clean:
	@echo "----------Cleaning project:[ colaRecursivaA - Debug ]----------"
	@cd "colaRecursivaA" && "$(MAKE)" -f  "colaRecursivaA.mk" clean
