.PHONY: clean All

All:
	@echo "----------Building project:[ pilatest - Debug ]----------"
	@cd "pilatest" && "$(MAKE)" -f  "pilatest.mk"
clean:
	@echo "----------Cleaning project:[ pilatest - Debug ]----------"
	@cd "pilatest" && "$(MAKE)" -f  "pilatest.mk" clean
