.PHONY: clean All

All:
	@echo "----------Building project:[ randomA - Debug ]----------"
	@cd "randomA" && "$(MAKE)" -f  "randomA.mk"
clean:
	@echo "----------Cleaning project:[ randomA - Debug ]----------"
	@cd "randomA" && "$(MAKE)" -f  "randomA.mk" clean
