.PHONY: clean All

All:
	@echo "----------Building project:[ lista - Debug ]----------"
	@cd "lista" && "$(MAKE)" -f  "lista.mk"
clean:
	@echo "----------Cleaning project:[ lista - Debug ]----------"
	@cd "lista" && "$(MAKE)" -f  "lista.mk" clean
