.PHONY: clean All

All:
	@echo "----------Building project:[ punteros2A - Debug ]----------"
	@cd "punteros2A" && "$(MAKE)" -f  "punteros2A.mk"
clean:
	@echo "----------Cleaning project:[ punteros2A - Debug ]----------"
	@cd "punteros2A" && "$(MAKE)" -f  "punteros2A.mk" clean
