.PHONY: clean All

All:
	@echo "----------Building project:[ monticulo - Debug ]----------"
	@cd "monticulo" && "$(MAKE)" -f  "monticulo.mk"
clean:
	@echo "----------Cleaning project:[ monticulo - Debug ]----------"
	@cd "monticulo" && "$(MAKE)" -f  "monticulo.mk" clean
