.PHONY: clean All

All:
	@echo "----------Building project:[ insercciondatos - Debug ]----------"
	@cd "insercciondatos" && "$(MAKE)" -f  "insercciondatos.mk"
clean:
	@echo "----------Cleaning project:[ insercciondatos - Debug ]----------"
	@cd "insercciondatos" && "$(MAKE)" -f  "insercciondatos.mk" clean
