.PHONY: clean All

All:
	@echo "----------Building project:[ punterosA - Debug ]----------"
	@cd "punterosA" && "$(MAKE)" -f  "punterosA.mk"
clean:
	@echo "----------Cleaning project:[ punterosA - Debug ]----------"
	@cd "punterosA" && "$(MAKE)" -f  "punterosA.mk" clean
