.PHONY: clean All

All:
	@echo "----------Building project:[ matrizA - Debug ]----------"
	@cd "matrizA" && "$(MAKE)" -f  "matrizA.mk"
clean:
	@echo "----------Cleaning project:[ matrizA - Debug ]----------"
	@cd "matrizA" && "$(MAKE)" -f  "matrizA.mk" clean
